### PR TITLE
Javadoc improvements

### LINKED ISSUE #155: Documentation Effort
# Why?

Treasury's documentation could be considered relatively good at this point, however, since we use a concurrency system, it is more difficult to use. Therefore we need to provide very solid documentation if we have any hopes of gaining adoption in the community.

***

# Things to do

### Cover all the updates since 1.0.0
Basically update the wiki with all the changes that occurred afterwards (2.0.0 included).

- [x] All unlisted Wiki pages.
- [x] https://github.com/ArcanePlugins/Treasury/wiki/Permissions
- [x] https://github.com/ArcanePlugins/Treasury/wiki/messages.yml
- [x] https://github.com/ArcanePlugins/Treasury/wiki/settings.yml
- [x] https://github.com/ArcanePlugins/Treasury/wiki/Treasury-Placeholders

### Add 'Getting Started' page - short and concise version to get started with Treasury.

- [x] Page created
- [x] Created draft
- [x] Refined content

The average developer probably doesn't want to read all the details about the economy API, rather, just want to know how to do these simple operations:

* add maven repo
* get the economy provider from the service registry
* get/set balance, withdraw, deposit to player accounts
  * We will absolutely be showing CompletableFuture examples on this page. We should still touch on just the standard EconomySubscriber at the bottom of the page, but we must promote Futures over Subscribers for cleanliness and ease of use.
* Although we must heavily recommend against doing so, we should show how developers can run the CompletableFutures synchronously in the case that it is unfeasible for them to use Treasury due to poorly designed code that lacks concurrency.

Thank you to AlonsoAliaga for suggesting this.

## Javadocs

Javadocs must be improved as a whole. See #250.

### PR DESCRIPTION
**Pull request by MrIvanPlays**
I've gone through the whole API and modified the javadocs where necessary.

Aims to resolve #155

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
@lokka30 you might want to do the same and push all the changes you think necessary.

**Comment by lokka30** [comment]
I think we should not need to have a PR to work on javadocs, let's just commit them straight into the development branch (unless we are making a mass change to them).

**Comment by MrIvanPlays** [comment]
Then squash and merge this.

**Comment by lokka30** [comment]
Squashed and merged - thanks as always, Ivan. Note that this does not completely resolve #155, I still have a lot of work to do on the Wiki once we are completely happy with the code state of the APIs for v2.

**Pull request merged**
